#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Shuma Kasai
# SPDX-License-Indentifier: BSD-3-Clause

import sys


def tonum(s):
    try:
        ans += int(line)
    except:
        ans += float(line)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)
